#!/usr/local/bin/php
<?php
$login=$argv[1];
$config=parse_ini_file(dirname(__FILE__)."/config");
$loginDB = new mysqli($config['host'], $config['username'], $config['password'], $config['database']);
$ipq='SELECT `IP` FROM `users` WHERE `login`="'.$login.'"';
$ip=$loginDB->query($ipq);
           while ($line2 = mysqli_fetch_assoc($ip)) {
                foreach($line2 as $ipval) {
                                $macq='SELECT `mac` from `nethosts` WHERE `ip`="'.$ipval.'"';
                                $mac=$loginDB->query($macq);
                                   while ($line3 = mysqli_fetch_assoc($mac)) {
                                   foreach($line3 as $macval) {
                                   print($macval);
                                   }
                                  }
                           }    
                        }

?>