#!/usr/local/bin/php
<?php
$login=$argv[1];
$config=parse_ini_file(dirname(__FILE__)."/config");
$loginDB = new mysqli($config['host'], $config['username'], $config['password'], $config['database']);
$ipq='SELECT `IP` FROM `users` WHERE `login`="'.$login.'"';
$ip=$loginDB->query($ipq)
           while ($line2 = mysqli_fetch_assoc($ip)) {
                foreach($line2 as $ipval) {
                                $nasq='select `nas`.`nasip` from `nethosts` join  `nas` on (`nas`.`netid` = `nethosts`.`netid`) where `nethosts`.`ip` = "'.$ipval.'"';
                                $nas=$loginDB->query($nasq);
                                   while ($line3 = mysqli_fetch_assoc($nas)) {
                                   foreach($line3 as $nasip) {
                                   print($nasip);
                                   }
                                  }
                           }    
                        }

?>
