#!/usr/local/bin/php
<?php
$login=$argv[1];
$config=parse_ini_file(dirname(__FILE__)."/config");
$loginDB = new mysqli($config['host'], $config['username'], $config['password'], $config['database']);
$query = 'SELECT `speed` FROM `userspeeds` where `login`= "'.$login.'"';
$result = $loginDB->query($query);
while ($line = mysqli_fetch_assoc($result)) {
foreach ($line as $col_value) {
if ($col_value) {
 print ($col_value);
  } else {
 $tarq='SELECT `Tariff` FROM users WHERE `login`="'.$login.'"';
 $tar=$loginDB->query($tarq);
           while ($line2 = mysqli_fetch_assoc($tar)) {
                foreach($line2 as $tarval) {
                                $speedq='SELECT `speeddown` from `speeds` WHERE `tariff`="'.$tarval.'"';
                                $speed=$loginDB->query($speedq);
                                   while ($line3 = mysqli_fetch_assoc($speed)) {
                                   foreach($line3 as $speedval) {
                                   print($speedval);
                                   }
                                  }
                           }    
                        }
  }

 }
}
?>