<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a bank_details_lookup, providing access to its
 * attributes
 *
 * @property-read $available_debit_schemes
 * @property-read $bank_name
 * @property-read $bic
 */
class BankDetailsLookup extends BaseResource
{
    protected $model_name = "BankDetailsLookup";

    /**
     * Array of [schemes](#mandates_scheme) supported for this bank account.
     * This will be an empty array if the bank account is not reachable by any
     * schemes.
     */
    protected $available_debit_schemes;

    /**
     * The name of the bank with which the account is held (if available).
     */
    protected $bank_name;

    /**
     * ISO 9362 SWIFT BIC of the bank with which the account is held. <p
     * class="notice">Even if no BIC is returned for an account, GoCardless may
     * still be able to collect payments from it - you should refer to the
     * `available_debit_schemes` attribute to determine reachability.</p>
     */
    protected $bic;

}
