<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a customer_notification, providing access to its
 * attributes
 *
 * @property-read $action_taken
 * @property-read $action_taken_at
 * @property-read $action_taken_by
 * @property-read $id
 * @property-read $links
 * @property-read $type
 */
class CustomerNotification extends BaseResource
{
    protected $model_name = "CustomerNotification";

    /**
     * The action that was taken on the notification. Currently this can only be
     * `handled`,
     * which means the integrator sent the notification themselves.
     */
    protected $action_taken;

    /**
     * Fixed [timestamp](#api-usage-time-zones--dates), recording when this
     * action was taken.
     */
    protected $action_taken_at;

    /**
     * A string identifying the integrator who was able to handle this
     * notification.
     */
    protected $action_taken_by;

    /**
     * The id of the notification.
     */
    protected $id;

    /**
     * 
     */
    protected $links;

    /**
     * The type of notification the customer shall receive.
     */
    protected $type;

}
