<?php
/**
 * WARNING: Do not edit by hand, this file was generated by Crank:
 *
 * https://github.com/gocardless/crank
 */

namespace GoCardlessPro\Resources;

/**
 * A thin wrapper around a mandate_import_entry, providing access to its
 * attributes
 *
 * @property-read $created_at
 * @property-read $links
 * @property-read $record_identifier
 */
class MandateImportEntry extends BaseResource
{
    protected $model_name = "MandateImportEntry";

    /**
     * Fixed [timestamp](#api-usage-time-zones--dates), recording when this
     * resource was created.
     */
    protected $created_at;

    /**
     * Related resources
     */
    protected $links;

    /**
     * A unique identifier for this entry, which you can use (once the import
     * has been
     * processed by GoCardless) to identify the records that have been created.
     */
    protected $record_identifier;

}
