CREATE TABLE IF NOT EXISTS `garage_cars` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vendor` VARCHAR(40) NOT NULL,
  `model` VARCHAR(40) NOT NULL,
  `number` VARCHAR(20) DEFAULT NULL,
  `vin` VARCHAR(40) DEFAULT NULL,
  `year` INT(11) DEFAULT NULL,
  `power` INT(11) DEFAULT NULL,
  `engine` INT(11) DEFAULT NULL,
  `fueltype` VARCHAR(16) DEFAULT NULL,
  `gastank` INT(11) DEFAULT NULL,
  `weight` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `garage_drivers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employeeid` INT(11) NOT NULL,
  `carid` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
