CREATE TABLE IF NOT EXISTS `ptv_subscribers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `subscriberid` INT(11) NOT NULL,
  `login` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `ptv_tariffs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `serviceid` INT(11) NOT NULL,
  `main` tinyint(1) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `chans` VARCHAR(42) DEFAULT NULL,
  `fee` DOUBLE NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;