CREATE TABLE IF NOT EXISTS `bgppeers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(64) DEFAULT NULL,
  `name` VARCHAR(64) DEFAULT NULL,
  `short` VARCHAR(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ip` (`ip`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

