;map center coordinates. Geo location if empty. For example: "50.4437, 30.5162"
CENTER="48.52584946874239, 25.03798691368117"
;default map zoom
ZOOM=14
;default map type. roadmap, satellite, hybrid, terrain available.
TYPE="roadmap"
;Use canvas rendering
CANVAS_RENDER=1
;device finder zoom
FINDING_ZOOM=17
;Hightlight area with circle when device found
FINDING_CIRCLE=1
;Leaflet custom tile layer. Examples:
; Mapbox: https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=somesecrettoken
; OSM: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
; Visicom: https://tms{s}.visicom.ua/2.0.0/planet3/base/{z}/{x}/{y}.png?key=YOUR_API_KEY
; Google roadmaps: http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}
; Google hybryd: http://{s}.google.com/vt/lyrs=s,h&x={x}&y={y}&z={z}
; Google satellite: http://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}
; Google terrain: http://{s}.google.com/vt/lyrs=p&x={x}&y={y}&z={z}
; KaminariTile cache server: https://your.tile.server.ua/kaminaritile/?t={s}_{z}_{x}_{y}
LEAFLET_TILE_LAYER="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
