#!/usr/local/bin/php
<?php
$login=$argv[1];
$cfid=$argv[2];
include('mysql.php');
$ipq='SELECT `content` FROM `cfitems` WHERE `login`="'.$login.'" AND `typeid`="'.$cfid.'"';
$ip=DB_query($ipq);
           while ($line2 = DB_fetch_array($ip)) {
                $ipval = $line2['content'];
                                   print($ipval);
                        }

?>
