#!/usr/local/bin/php
<?php
$login = $argv[1];
$cfid = $argv[2];
include('mysql.php');
$query = 'SELECT * FROM `netextpools` WHERE `login`="' . $login . '"';
$raw = DB_query($query);
while ($line2 = DB_fetch_array($raw)) {
    print($line2['pool'] . '/' . $line2['netmask'] . "\n");
}
?>
