#!/usr/local/bin/php
<?php
$login=$argv[1];
include('mysql.php');
$ipq='SELECT `Tariff` FROM `users` WHERE `login`="'.$login.'"';
$ip=DB_query($ipq);
           while ($line2 = DB_fetch_array($ip)) {
                $tarrif = $line2['Tariff'];
                                   print($tarrif); 
                        }

?>
