#!/usr/local/bin/php
<?php if ( !empty($argv) && $argc == 2 ) {

        // Environment:
        define('ENVIRONMENT', basename($argv[0]));

        //  User's login:
        if (isset($argv[1])) {
            define('LOGIN', $argv[1]);
        } else define('LOGIN', NULL);

        // Paths:
        define('BASEPATH', __DIR__ . '/');
        define('SYSTEM', BASEPATH . 'system/');
        define('DBPATH',  SYSTEM . 'database/');
        define('NASPATH', SYSTEM . 'executer/');
        define('LOGPATH', SYSTEM . 'log/');

        // Driver's extention:
        define('EXT', '.drv');

        // Turn off PHP error reporting:
        error_reporting(0);

        // Unset all resived arguments and their amount:
        unset($argv, $argc);
        
        // Continue...
        include_once(SYSTEM . 'ubilling.cls');
        new Ubilling();
        
    } else exit('Only STG can run script!');
?>